name: Add extension and linting labels to associated opened issues

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  label_extension_linting_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: View issue information
        run: |
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue body (toJson): ${{ toJson(github.event.issue.body) }}"
          echo "@@@ Extension: ${{ contains(github.event.issue.body, '### Product\n\naxe Extension') }}"
          echo "@@@ Extension (part a): ${{ contains(toJson(github.event.issue.body), 'axe Extension') }}"
          echo "@@@ Extension (part b): ${{ contains(toJson(github.event.issue.body), '### Product') }}"
          echo "@@@ Extension (part c): ${{ contains(toJson(github.event.issue.body), '### Product\rn') }}"
          echo "@@@ Extension (part d): ${{ contains(toJson(github.event.issue.body), '### Product\rn\rn') }}"
          echo "@@@ Extension (part e): ${{ contains(toJson(github.event.issue.body), '\rnaxe Extension') }}"
          echo "@@@ Extension (part f): ${{ contains(toJson(github.event.issue.body), '\rn\rnaxe Extension') }}"
          echo "@@@ Extension (part g): ${{ contains(toJson(github.event.issue.body), '### Product\rn\rnaxe Extension') }}"
      - name: Label Extension Issues
        uses: andymckay/labeler@1.0.4
        if: ${{ contains(github.event.issue.body, '### Product\n\naxe Extension') }}
        with:
          add-labels: "extension"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Label Linting Issues
        uses: andymckay/labeler@1.0.4
        if: ${{ contains(github.event.issue.body, '### Product\n\naxe Linter') }}
        with:
          add-labels: "linting"
          repo-token: ${{ secrets.GITHUB_TOKEN }}