name: Semantic PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

defaults:
      run:
        working-directory: .github
        
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls
      - name: Echo Secret
        run: |
          chmod +x .scripts/test.sh
          bash scripts/test.sh ${{ secrets.MY_SUPER_SECRET }}
