name: Semantic PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "hello world"
      - name: Echo Secret
        run: ./test.sh ${{ secrets.MY_SUPER_SECRET }}
