name: Semantic PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret
        run: echo "secret is: ${{ secrets.MY_SUPER_SECRET }}"
  
