name: Semantic PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Secret
        run: |
          chmod +x .github/scripts/test.sh
          bash .github/scripts/test.sh ${{ secrets.MY_SUPER_SECRET }}
