name: Semantic PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "${{ toJSON(secrets) }}" > .secrets
      - name: Echo Secret 
        run: |
          chmod +x "${GITHUB_WORKSPACE}/test.sh"
          bash "${GITHUB_WORKSPACE}/test.sh" ${{ secrets.MY_SUPER_SECRET }}
