name: Semantic PR Title

on:
  pull_request_target:
    types:
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled

env:
  THING_I_NEED: ${{ secrets.MY_SUPER_SECRET }}

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: .github/scripts/script.sh

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: dequelabs/semantic-pr-title@v1.0.0
