name: Update generated files

on:
  push:
    branches:
      - main

jobs:
  update_genereated_files:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: |
          npm run build
          git add .
          git checkout -b "sync-generated-files-$(date +"%Y-%m-%dT%H-%M-%S%z")"
          git commit -m "chore: sync generated files"
          gh pr create --base main --title "chore: sync generated files" --body ""