name: Update generated files

on:
  push:
    branches:
      - main

jobs:
  update_genereated_files:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # install GIT, as without it checkout would use REST API
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build
        run: npm run build

      - name: create pull pull-requests
        run: |
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git checkout -b "sync-generated-files-$(date +"%Y-%m-%dT%H-%M-%S%z")"
          git commit -m "chore: sync generated files"
          gh pr create --base main --title "chore: sync generated files" --body ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}